### ISSUE TITLE
transcode apte 1965 literary sources

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/temp_corrections_ap90#1]
@sanskritisampada 

There is now a pdf of literary source abbreviations, from a version of Apte (see https://github.com/sanskrit-lexicon/AP90/issues/17#issuecomment-848787358).

The task is to make a text file of these abbreviations.

Use the file Apte.S2H.works.txt, which I've started.
Instructions are there.

So, do a pull of temp_corrections_ap90, and you should be ready to go!

**Comment by gasyoun** [comment]
> The task is to make a text file of these abbreviations.

Thanks, Jim.

**Comment by Andhrabharati** [comment]
@drdhaval2785 
this work having been completed, the issue can be closed.
